apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: training-app
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  CORS_ORIGINS: "http://localhost:3000,http://training.localtest.me"
